# Generated by Django 4.2.1 on 2023-05-24 09:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreGlav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Основной глава:')),
            ],
            options={
                'verbose_name': 'Основной Глава',
            },
        ),
        migrations.CreateModel(
            name='Glav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='глава: ')),
                ('core_glav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coreglav', verbose_name='Основной глава: ')),
            ],
            options={
                'verbose_name': 'Глава',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('glav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.glav', verbose_name='Глава: ')),
            ],
        ),
    ]
